packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  nodent-runtime: false
  nx: false
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
