name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Playground prepare
        run: npm run dev:prepare

      - name: Test
        run: npm run test
