import { useEffect, useMemo, useRef } from 'react';
import type {
  FormEngine,
  FormValidator,
  JsonSchema,
  NodeProcessor,
  PresentationModel,
  SchemaSource,
  UISchemaElement,
} from '@jsonforms/core';
import { createFormEngine, jsonSchemaSource } from '@jsonforms/core';
import type { RendererRegistryEntry } from './context';
import { JsonFormsContext } from './context';
import { NodeDispatch } from './NodeDispatch';

export interface JsonFormsChangeEvent {
  data: unknown;
  model: PresentationModel;
}

export interface JsonFormsProps {
  /** A pre-configured engine; mutually exclusive with the config props below. */
  engine?: FormEngine;
  /** Initial form data. Subsequent changes flow through the engine. */
  data?: unknown;
  /** Convenience: builds a `jsonSchemaSource` from this JSON Schema. */
  schema?: JsonSchema;
  /** Explicit schema source; takes precedence over `schema`. */
  schemaSource?: SchemaSource;
  /** UI structure; generated by the schema source when omitted. */
  uischema?: UISchemaElement;
  validator?: FormValidator;
  processors?: readonly NodeProcessor[];
  renderers: readonly RendererRegistryEntry[];
  onChange?: (event: JsonFormsChangeEvent) => void;
}

export const JsonForms = ({
  engine,
  data,
  schema,
  schemaSource,
  uischema,
  validator,
  processors,
  renderers,
  onChange,
}: JsonFormsProps) => {
  const resolvedEngine = useMemo(() => {
    if (engine !== undefined) {
      return engine;
    }
    const source =
      schemaSource ??
      (schema !== undefined ? jsonSchemaSource(schema) : undefined);
    if (source === undefined) {
      throw new Error(
        '<JsonForms> requires either an engine, a schemaSource, or a schema.',
      );
    }
    return createFormEngine({
      schemaSource: source,
      data,
      uischema,
      validator,
      processors,
    });
    // `data` is deliberately not a dependency: it is the initial value; all
    // subsequent data changes are driven through engine commands.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [engine, schema, schemaSource, uischema, validator, processors]);

  const contextValue = useMemo(
    () => ({ engine: resolvedEngine, renderers }),
    [resolvedEngine, renderers],
  );

  const onChangeRef = useRef(onChange);
  useEffect(() => {
    onChangeRef.current = onChange;
  }, [onChange]);

  useEffect(() => {
    const emit = () =>
      onChangeRef.current?.({
        data: resolvedEngine.getData(),
        model: resolvedEngine.getModel(),
      });
    emit();
    return resolvedEngine.subscribe(emit);
  }, [resolvedEngine]);

  return (
    <JsonFormsContext.Provider value={contextValue}>
      <NodeDispatch id={resolvedEngine.getModel().rootId} />
    </JsonFormsContext.Provider>
  );
};
