'use strict';
angular.module('makeithappen').config(['$routeProvider',
    function($routeProvider) {
        $routeProvider.when('/person', {
            templateUrl: 'app/person/person.html',
            controller: 'PersonController',
            controllerAs: 'vm'
        }).when('/masterdetail', {
           templateUrl: 'app/masterdetail/masterdetail.html',
           controller: 'MasterDetailController',
           controllerAs: 'vm'
        }).when('/resolve', {
            templateUrl: 'app/resolve/resolve.html',
            controller: 'ResolveController',
            controllerAs: 'vm'
        }).when('/editor', {
            templateUrl: 'app/editor/editor.html',
            controller: 'EditorController',
            controllerAs: 'vm'
        }).when('/custom', {
            templateUrl: 'app/custom/custom.html',
            controller: 'CustomController',
            controllerAs: 'vm'
        }).when('/default-ui', {
            templateUrl: 'app/default-ui/default-ui.html',
            controller: 'DefaultUISchemaController',
            controllerAs: 'vm'
        }).when('/default-schema', {
            templateUrl: 'app/default/default-schema.html',
            controller: 'DefaultSchemaController',
            controllerAs: 'vm'
        }).when('/placeholder-users/:id?', {
            templateUrl: 'app/placeholder/placeholder-users.html',
            controller: 'PlaceholderUserController',
            controllerAs: 'vm'
        }).when('/polymer', {
            templateUrl: 'app/polymer/polymer.html',
            controller: 'PolymerController',
            controllerAs: 'vm'
        }).when('/arrays', {
            templateUrl: 'app/arrays/arrays.html',
            controller: 'ArraysController',
            controllerAs: 'vm'
        }).when('/async', {
            templateUrl: 'app/async/async.html',
            controller: 'AsyncController',
            controllerAs: 'vm'
        }).when('/category', {
            templateUrl: 'app/category/category.html',
            controller: 'CategoryController',
            controllerAs: 'vm'
        }).when('/layouts', {
            templateUrl: 'app/layouts/layouts.html',
            controller: 'LayoutsController',
            controllerAs: 'vm'
        }).when('/rule', {
            templateUrl: 'app/rule/rule.html',
            controller: 'RuleController',
            controllerAs: 'vm'
        }).otherwise({
            redirectTo: '/person'
        });
    }
]);
