import type {
  NodeId,
  PresentationModel,
  PresentationNode,
} from '../model/nodes';
import type { UISchemaElement } from '../model/uischema';
import type { SchemaSource } from '../schema/source';
import type { FormValidator, ValidationIssue } from '../validation/validation';
import { noValidation } from '../validation/validation';
import type { FormCommand } from './commands';
import type { NodeProcessor } from './build';
import { buildModel } from './build';
import type { IssueDisplayPolicy } from './issue-display';
import { alwaysShowIssues, showIssuesWhenTouched } from './issue-display';
import { setAtPointer } from '../util/pointer';

/** Notification sent to engine subscribers after every model update. */
export interface ModelDelta {
  version: number;
  /** Nodes that are new or whose content changed. */
  upserted: readonly PresentationNode[];
  /** Ids of nodes that no longer exist. */
  removed: readonly NodeId[];
  /** The current form data. */
  data: unknown;
}

/** Form-wide options. */
export interface FormConfig {
  /** Show validation issues only after a control was touched. Default: `false`. */
  showIssuesOnTouch?: boolean;
}

export interface FormEngineOptions {
  schemaSource: SchemaSource;
  /** Initial form data. */
  data?: unknown;
  /** UI structure; generated by the schema source when omitted. */
  uischema?: UISchemaElement;
  validator?: FormValidator;
  config?: Readonly<FormConfig>;
  /**
   * Decides which validation issues land on nodes; overrides the
   * config-derived default (`alwaysShowIssues`, or `showIssuesWhenTouched`
   * with `config.showIssuesOnTouch`).
   */
  issueDisplay?: IssueDisplayPolicy;
  processors?: readonly NodeProcessor[];
}

/**
 * The stateful form runtime: owns data and presentation model, processes
 * commands, and notifies subscribers with node-granular deltas.
 */
export interface FormEngine {
  getModel(): PresentationModel;
  getNode(id: NodeId): PresentationNode | undefined;
  getData(): unknown;
  dispatch(command: FormCommand): void;
  /** Subscribes to all model updates. Returns an unsubscribe function. */
  subscribe(listener: (delta: ModelDelta) => void): () => void;
  /** Subscribes to updates of a single node. Returns an unsubscribe function. */
  subscribeNode(id: NodeId, listener: () => void): () => void;
}

export const createFormEngine = (options: FormEngineOptions): FormEngine => {
  const source = options.schemaSource;
  const uischema = options.uischema ?? source.generateUISchema();
  const validator = options.validator ?? noValidation;
  const config = options.config ?? {};
  const issueDisplay =
    options.issueDisplay ??
    (config.showIssuesOnTouch === true
      ? showIssuesWhenTouched
      : alwaysShowIssues);
  const processors = options.processors ?? [];

  let data: unknown = options.data;
  let issues: readonly ValidationIssue[] = [];
  let touched: ReadonlySet<NodeId> = new Set();
  let model: PresentationModel;
  let validationRun = 0;

  const modelListeners = new Set<(delta: ModelDelta) => void>();
  const nodeListeners = new Map<NodeId, Set<() => void>>();

  const build = (previous: PresentationModel | undefined): PresentationModel =>
    buildModel({
      uischema,
      data,
      source,
      issues,
      issueDisplay,
      touched,
      processors,
      previous,
      version: (previous?.version ?? 0) + 1,
    });

  const rebuild = (): void => {
    const previous = model;
    const next = build(previous);
    model = next;
    const upserted = Object.values(next.nodes).filter(
      (node) => previous.nodes[node.id] !== node,
    );
    const removed = Object.keys(previous.nodes).filter(
      (id) => next.nodes[id] === undefined,
    );
    const delta: ModelDelta = {
      version: next.version,
      upserted,
      removed,
      data,
    };
    for (const listener of [...modelListeners]) {
      listener(delta);
    }
    for (const id of [...upserted.map((node) => node.id), ...removed]) {
      const listeners = nodeListeners.get(id);
      if (listeners) {
        for (const listener of [...listeners]) {
          listener();
        }
      }
    }
  };

  const runValidation = (): void => {
    const result = validator.validate(data);
    if (result instanceof Promise) {
      const run = ++validationRun;
      void result.then((resolved) => {
        if (run !== validationRun) {
          return;
        }
        issues = resolved;
        rebuild();
      });
      return;
    }
    validationRun++;
    issues = result;
  };

  const dispatch = (command: FormCommand): void => {
    switch (command.type) {
      case 'set-value': {
        data = setAtPointer(data, command.path, command.value);
        runValidation();
        rebuild();
        break;
      }
      case 'touch': {
        if (touched.has(command.nodeId)) {
          return;
        }
        const next = new Set(touched);
        next.add(command.nodeId);
        touched = next;
        rebuild();
        break;
      }
    }
  };

  runValidation();
  model = build(undefined);

  return {
    getModel: () => model,
    getNode: (id) => model.nodes[id],
    getData: () => data,
    dispatch,
    subscribe: (listener) => {
      modelListeners.add(listener);
      return () => {
        modelListeners.delete(listener);
      };
    },
    subscribeNode: (id, listener) => {
      let listeners = nodeListeners.get(id);
      if (listeners === undefined) {
        listeners = new Set();
        nodeListeners.set(id, listeners);
      }
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
        if (listeners.size === 0) {
          nodeListeners.delete(id);
        }
      };
    },
  };
};
